from __future__ import annotations

import argparse
from pathlib import Path


def as_posix(path: Path) -> str:
    return path.resolve().as_posix()


def build_config(args: argparse.Namespace) -> str:
    data_root = as_posix(args.data_root)
    meta_info = as_posix(args.meta_info)
    pretrain_g = args.pretrain_g.replace("\\", "/")
    pretrain_d = args.pretrain_d.replace("\\", "/")

    return f"""# Real-ESRGAN paired-data fine-tuning config for the SRGD course project.
# Generated by scripts/write_realesrgan_config.py.

name: finetune_RealESRGANx4plus_SRGD_pairdata
model_type: RealESRGANModel
scale: 4
num_gpu: auto
manual_seed: 0

l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False
high_order_degradation: False

datasets:
  train:
    name: SRGD
    type: RealESRGANPairedDataset
    dataroot_gt: {data_root}
    dataroot_lq: {data_root}
    meta_info: {meta_info}
    io_backend:
      type: disk
    gt_size: {args.gt_size}
    use_hflip: True
    use_rot: False
    use_shuffle: true
    num_worker_per_gpu: {args.workers}
    batch_size_per_gpu: {args.batch_size}
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

path:
  pretrain_network_g: {pretrain_g}
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: {pretrain_d}
  param_key_d: params
  strict_load_d: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float {args.lr}
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float {args.lr}
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [{args.total_iter}]
    gamma: 0.5
  total_iter: {args.total_iter}
  warmup_iter: -1
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      conv1_2: 0.1
      conv2_2: 0.1
      conv3_4: 1
      conv4_4: 1
      conv5_4: 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1
  net_d_iters: 1
  net_d_init_iters: 0

logger:
  print_freq: 100
  save_checkpoint_freq: !!float {args.save_freq}
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write a Real-ESRGAN paired-data fine-tuning YAML.")
    parser.add_argument("--data-root", type=Path, required=True, help="Dataset root used for dataroot_gt/lq.")
    parser.add_argument("--meta-info", type=Path, required=True, help="meta_info txt from prepare_pairs.py.")
    parser.add_argument("--out", type=Path, required=True, help="Output YAML path.")
    parser.add_argument("--batch-size", type=int, default=4, help="batch_size_per_gpu.")
    parser.add_argument("--workers", type=int, default=2, help="num_worker_per_gpu.")
    parser.add_argument("--gt-size", type=int, default=256, help="Training crop size.")
    parser.add_argument("--total-iter", type=int, default=20000, help="Total fine-tuning iterations.")
    parser.add_argument("--save-freq", type=int, default=1000, help="Checkpoint save frequency.")
    parser.add_argument("--lr", default="1e-4", help="Generator/discriminator learning rate.")
    parser.add_argument(
        "--pretrain-g",
        default="experiments/pretrained_models/RealESRGAN_x4plus.pth",
        help="Generator checkpoint path as seen from the Real-ESRGAN repo.",
    )
    parser.add_argument(
        "--pretrain-d",
        default="experiments/pretrained_models/RealESRGAN_x4plus_netD.pth",
        help="Discriminator checkpoint path as seen from the Real-ESRGAN repo.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_config(args), encoding="utf-8")
    print(f"Wrote Real-ESRGAN config to {args.out}")


if __name__ == "__main__":
    main()
