from __future__ import annotations

import argparse
from pathlib import Path


def as_posix(path: Path) -> str:
    return path.resolve().as_posix()


def build_milestones(total_iter: int) -> str:
    # Decay at 60% and 90% of training so the LR schedule is actually used.
    m1 = max(1, round(total_iter * 0.6))
    m2 = max(m1 + 1, round(total_iter * 0.9))
    return f"[{m1}, {m2}]"


def build_config(args: argparse.Namespace) -> str:
    data_root = as_posix(args.data_root)
    meta_info = as_posix(args.meta_info)
    pretrain_g = args.pretrain_g.replace("\\", "/")
    pretrain_d = args.pretrain_d.replace("\\", "/")
    milestones = build_milestones(args.total_iter)
    use_rot = "True" if args.use_rot else "False"
    prefetch = args.prefetch_mode if args.prefetch_mode else "~"
    pin_memory = "    pin_memory: True\n" if prefetch == "cuda" else ""

    # Clamp warmup and d_init so they stay within training length.
    warmup_iter = min(args.warmup_iter, max(0, args.total_iter - 1))
    d_init_iters = min(args.d_init_iters, max(0, args.total_iter - 1))

    val_block = ""
    if args.val_meta_info:
        val_meta = as_posix(args.val_meta_info)
        val_block = f"""
  val:
    name: SRGD_val
    type: RealESRGANPairedDataset
    dataroot_gt: {data_root}
    dataroot_lq: {data_root}
    meta_info: {val_meta}
    io_backend:
      type: disk
    gt_size: ~
    use_hflip: False
    use_rot: False
    use_shuffle: false
    num_worker_per_gpu: 2
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
"""

    return f"""# Real-ESRGAN paired-data fine-tuning config for the SRGD course project.
# Generated by scripts/write_realesrgan_config.py.

name: finetune_RealESRGANx4plus_SRGD_pairdata
model_type: RealESRGANModel
scale: 4
num_gpu: auto
manual_seed: 0

l1_gt_usm: True
percep_gt_usm: True
gan_gt_usm: False
high_order_degradation: False

datasets:
  train:
    name: SRGD
    type: RealESRGANPairedDataset
    dataroot_gt: {data_root}
    dataroot_lq: {data_root}
    meta_info: {meta_info}
    io_backend:
      type: disk
    gt_size: {args.gt_size}
    use_hflip: True
    use_rot: {use_rot}
    use_shuffle: true
    num_worker_per_gpu: {args.workers}
    batch_size_per_gpu: {args.batch_size}
    dataset_enlarge_ratio: {args.enlarge_ratio}
    prefetch_mode: {prefetch}
{pin_memory.rstrip()}
{val_block}
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64
  skip_connection: True

path:
  pretrain_network_g: {pretrain_g}
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: {pretrain_d}
  param_key_d: params
  strict_load_d: true
  resume_state: ~

train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float {args.lr_g}
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float {args.lr_d}
    weight_decay: 0
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: {milestones}
    gamma: 0.5
  total_iter: {args.total_iter}
  warmup_iter: {warmup_iter}
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      conv1_2: 0.1
      conv2_2: 0.1
      conv3_4: 1
      conv4_4: 1
      conv5_4: 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: !!float 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float {args.gan_weight}
  net_d_iters: 1
  net_d_init_iters: {d_init_iters}

logger:
  print_freq: 100
  save_checkpoint_freq: !!float {args.save_freq}
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

dist_params:
  backend: nccl
  port: 29500
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Write a Real-ESRGAN paired-data fine-tuning YAML.")
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--meta-info", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--val-meta-info", type=Path, default=None, help="Optional val meta_info txt for periodic eval.")
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--workers", type=int, default=2)
    parser.add_argument("--gt-size", type=int, default=256)
    parser.add_argument("--total-iter", type=int, default=20000)
    parser.add_argument("--save-freq", type=int, default=1000)
    parser.add_argument("--warmup-iter", type=int, default=500,
                        help="LR warmup steps. Set 0 to disable.")
    parser.add_argument("--d-init-iters", type=int, default=1000,
                        help="Train generator only for this many steps before enabling the discriminator.")
    parser.add_argument("--enlarge-ratio", type=int, default=1,
                        help="dataset_enlarge_ratio: repeat the dataset N times per epoch. "
                             "Use e.g. 100 when the dataset is small.")
    parser.add_argument("--use-rot", action="store_true", default=True,
                        help="Enable 90-degree rotation augmentation.")
    parser.add_argument("--no-rot", dest="use_rot", action="store_false")
    parser.add_argument("--prefetch-mode", default=None,
                        help="BasicSR prefetch mode: cuda, cpu, or ~ (disabled).")
    parser.add_argument("--lr-g", default="1e-4", help="Generator learning rate.")
    parser.add_argument("--lr-d", default="1e-4", help="Discriminator learning rate.")
    parser.add_argument("--lr", default=None,
                        help="Set both --lr-g and --lr-d to the same value (shorthand).")
    parser.add_argument("--gan-weight", default="1e-1",
                        help="GAN loss weight. Lower (e.g. 5e-2) is safer for fine-tuning.")
    # Legacy alias kept for backward compatibility with old notebook versions.
    parser.add_argument(
        "--pretrain-g",
        default="experiments/pretrained_models/RealESRGAN_x4plus.pth",
    )
    parser.add_argument(
        "--pretrain-d",
        default="experiments/pretrained_models/RealESRGAN_x4plus_netD.pth",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.lr is not None:
        args.lr_g = args.lr
        args.lr_d = args.lr
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_config(args), encoding="utf-8")
    print(f"Wrote Real-ESRGAN config to {args.out}")
    print(f"  total_iter={args.total_iter}  warmup={args.warmup_iter}  d_init={args.d_init_iters}")
    print(f"  milestones={build_milestones(args.total_iter)}  enlarge_ratio={args.enlarge_ratio}")


if __name__ == "__main__":
    main()
